package de.lbmaster.dayztoolbox.guis.servermanager;

public enum ServerEventType {
	EVENT_NONE, EVENT_START_BY_USER, EVENT_STOPREQUEST_RCON_BY_USER, EVENT_STOPREQUEST_BY_USER, EVENT_STOP_FORCE_BY_USER, EVENT_STOP_WINDOWS_REQUEST, EVENT_RCON_REACHABLE, EVENT_RCON_UNREACHABLE, EVENT_PROCESS_END, EVENT_CHRASH, EVENT_RESUME;

}
